version: '2'

networks:
  mynetwork:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/var/www/message-intelligence/
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mynetwork

  php:
    build: ./docker/php
    volumes:
      - .:/var/www/message-intelligence/
    networks:
      - mynetwork

  log:
    build: ./docker/php
    volumes:
      - .:/var/www/message-intelligence/
    command: ['tail', '-f', '/var/www/message-intelligence/web/storage/logs/laravel.log']
  
  redis:
    image: redis:latest
    networks:
      - mynetwork

  tf-server:
    image: bitnami/tensorflow-serving:latest
    volumes:
      - .:/var/www/message-intelligence/
      - ./docker/tf-server/tensorflow-serving.conf:/bitnami/tensorflow-serving/conf/tensorflow-serving.conf
    networks:
      - mynetwork

  tf-api:
    build: ./docker/tf-api
    volumes:
      - .:/var/www/message-intelligence/
    command: bash -c "cd /var/www/message-intelligence/ && python spell_api.py"
    networks:
      - mynetwork
  
  webpack:
    image: node:7
    volumes:
      - .:/var/www/message-intelligence/
    command: bash -c "cd /var/www/message-intelligence/web && npm install && npm run watch"


