version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - .:/var/www/message-intelligence/
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - app

  app:
    build: .
    volumes:
      - .:/var/www/message-intelligence/
    links:
      - redis
  
  redis:
    image: redis:latest

  tf-server:
    image: bitnami/tensorflow-serving:latest
    ports:
      - 8500:8500
    volumes:
      - ./conf/tensorflow-serving.conf:/bitnami/conf
      - .:/var/www/message-intelligence/

